INSERT INTO User (name, address, password) VALUES
('Alice Santos', 'Rua das Flores, 123', 'zeyOafF&Fs'),
('Bruno Costa', 'Av. Central, 456', 'da4E@JkDOL'),
('Carla Lima', 'Travessa do Sol, 789', 'r&jdu*ctEd'),
('Daniel Rocha', 'Rua do Norte, 321', 'EjFHn!7ZLr'),
('Eduarda Nunes', 'Rua Verde, 654', 'T1qM!R19Lo'),
('Fábio Silva', 'Av. Azul, 987', 'u6PS3qbJu0'),
('Gabriela Alves', 'Rua das Laranjeiras, 111', '$KJQYpusBc'),
('Henrique Lopes', 'Rua Nova, 222', 'Zx2V9t0apI'),
('Isabela Martins', 'Av. Brasil, 333', '0Lw*#U1hgU'),
('João Ferreira', 'Rua das Acácias, 444', 'nb3atAFW9W'),
('Karina Mendes', 'Rua do Campo, 555', '0&d0Ki0SLE'),
('Leonardo Braga', 'Av. Atlântica, 666', 'Rtkxn5o2Sc'),
('Mariana Cruz', 'Rua da Paz, 777', 'DhuVKP%qk$'),
('Nuno Duarte', 'Rua Estrela, 888', 'naXSjLUNnn'),
('Olívia Pinto', 'Av. do Mar, 999', 'S$utSUC*yq'),
('Paulo Ribeiro', 'Rua do Sol, 101', '0PE#0kE*0K'),
('Quésia Teixeira', 'Rua da Liberdade, 202', 'e!LHjNNI1M'),
('Ricardo Sousa', 'Av. dos Aliados, 303', 'z8$1rRX%%E'),
('Sofia Rocha', 'Rua Azul, 404', 'qtQNF@8Skm'),
('Tiago Neves', 'Rua das Rosas, 505', 'ZMxr4jb%dS'),
('Ursula Dias', 'Rua Branca, 606', 'Lp0hlqbY6*'),
('Vítor Amaral', 'Av. Verde, 707', 'UDozwDKspE'),
('Wanda Borges', 'Rua Clara, 808', '3s9g3s&QRb'),
('Xavier Gomes', 'Rua da República, 909', 'P6Qwt8VHFc'),
('Yasmin Henriques', 'Rua Azul, 112', 'm53$oHKiHy'),
('Zé Tavares', 'Av. Central, 113', '5oZP#ywlmG'),
('Alice Faria', 'Rua do Comércio, 114', 'Gv8ViY&E5e'),
('Bruno Almeida', 'Rua do Mercado, 115', 'Lmy4C#ImZE'),
('Carolina Rocha', 'Rua das Oliveiras, 116', '9bvMErL@Bb'),
('Diogo Melo', 'Av. do Porto, 117', '&m&DAyJ&SB'),
('Eva Monteiro', 'Rua das Pedras, 118', 'GU7UPnhdk3'),
('Fernando Serra', 'Rua do Castelo, 119', 'ncH5B$3mUb'),
('Gustavo Silva', 'Rua do Carmo, 120', 'OE1!4vAiHx'),
('Helena Moreira', 'Av. do Lago, 121', 'Qzxn954vWA'),
('Igor Figueira', 'Rua das Fontes, 122', 'KAKPhTKjY%'),
('Joana Lopes', 'Rua Nova, 123', '5mRT8BdWR6'),
('Kevin Pinto', 'Av. da Liberdade, 124', 'YK8x13&HAx'),
('Larissa Ramos', 'Rua Rosa, 125', '%SMF$OgjAN'),
('Miguel Teixeira', 'Rua dos Cravos, 126', 'TxyNzsQmfG'),
('Nádia Castro', 'Rua do Monte, 127', '&hN97M#3F%'),
('Otávio Lima', 'Rua Amarela, 128', 'n$f*hiuII6'),
('Patrícia Cunha', 'Rua do Mar, 129', 'HSGnuYDOXg'),
('Rafael Dias', 'Av. das Palmeiras, 130', 'b7iaEK$brC'),
('Sílvia Viana', 'Rua do Norte, 131', '5zHEGfdb*s'),
('Tomás Moreira', 'Rua da Serra, 132', 'Kd#qP1uihj'),
('Vanessa Reis', 'Av. da Praia, 133', 'sSoN#9CSg9'),
('William Rocha', 'Rua das Camélias, 134', 'eKsstMR3xJ'),
('Ximena Lopes', 'Av. das Águas, 135', 'vw1*ite5hb'),
('Yuri Matos', 'Rua das Nogueiras, 136', 'wTwz4SPlf0');
